# Generated by Django 5.2.8 on 2026-01-13 12:15

import accounts.validators
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Име (напр. Барбър')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Код (Slug)')),
                ('icon', models.CharField(default='🏢', max_length=10, verbose_name='Емоджи икона')),
            ],
            options={
                'verbose_name': 'Тип Бизнес',
                'verbose_name_plural': 'Типове Бизнеси',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на услугата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (лв. / €)')),
                ('duration', models.DurationField(verbose_name='Продължителност')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointment.businesscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на служителя')),
                ('start_work_time', models.TimeField(default=datetime.time(10, 0), verbose_name='Начало на смяна')),
                ('end_work_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Край на смяна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен служител')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='Потребителски акаунт')),
                ('services', models.ManyToManyField(related_name='professionals', to='appointment.service', verbose_name='Извършвани услуги')),
            ],
            options={
                'verbose_name': 'Служител',
                'verbose_name_plural': 'Служители',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Име на клиента')),
                ('client_phone', models.CharField(max_length=17, validators=[accounts.validators.PhoneNumberValidator()], verbose_name='Телефон за връзка')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имейл за контакт')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Час')),
                ('status', models.CharField(choices=[('pending', '⏳ Изчаква'), ('confirmed', '✅ Потвърден'), ('cancelled', '❌ Отказан'), ('completed', '🏁 Приключен')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.professional', verbose_name='Служител')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
