# Generated by Django 5.2.8 on 2025-12-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_professional_services_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='end_work_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Край на смяна'),
        ),
        migrations.AddField(
            model_name='professional',
            name='start_work_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Начало на смяна'),
        ),
    ]
